/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    brands: Brand;
    tags: Tag;
    products: Product;
    certificate: Certificate;
    carts: Cart;
    orders: Order;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    brands: BrandsSelect<false> | BrandsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    certificate: CertificateSelect<false> | CertificateSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    home: Home;
    iva: Iva;
    'company-info': CompanyInfo;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    iva: IvaSelect<false> | IvaSelect<true>;
    'company-info': CompanyInfoSelect<false> | CompanyInfoSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  address?: string | null;
  city?: string | null;
  cp?: string | null;
  province?:
    | (
        | 'Alava'
        | 'Albacete'
        | 'Alicante'
        | 'Almeria'
        | 'Asturias'
        | 'Avila'
        | 'Badajoz'
        | 'Barcelona'
        | 'Burgos'
        | 'Caceres'
        | 'Cadiz'
        | 'Cantabria'
        | 'Castellon'
        | 'Ciudad_Real'
        | 'Cordoba'
        | 'Cuenca'
        | 'Gerona'
        | 'Granada'
        | 'Guadalajara'
        | 'Guipuzcoa'
        | 'Huelva'
        | 'Huesca'
        | 'Baleares'
        | 'Jaen'
        | 'La_Coruna'
        | 'La_Rioja'
        | 'Las_Palmas'
        | 'Leon'
        | 'Lerida'
        | 'Lugo'
        | 'Madrid'
        | 'Malaga'
        | 'Murcia'
        | 'Navarra'
        | 'Orense'
        | 'Palencia'
        | 'Pontevedra'
        | 'Salamanca'
        | 'Tenerife'
        | 'Segovia'
        | 'Sevilla'
        | 'Soria'
        | 'Tarragona'
        | 'Teruel'
        | 'Toledo'
        | 'Valencia'
        | 'Valladolid'
        | 'Vizcaya'
        | 'Zamora'
        | 'Zaragoza'
      )
    | null;
  mailing_name?: string | null;
  mailing_address?: string | null;
  mailing_city?: string | null;
  mailing_cp?: string | null;
  mailing_province?:
    | (
        | 'Alava'
        | 'Albacete'
        | 'Alicante'
        | 'Almeria'
        | 'Asturias'
        | 'Avila'
        | 'Badajoz'
        | 'Barcelona'
        | 'Burgos'
        | 'Caceres'
        | 'Cadiz'
        | 'Cantabria'
        | 'Castellon'
        | 'Ciudad_Real'
        | 'Cordoba'
        | 'Cuenca'
        | 'Gerona'
        | 'Granada'
        | 'Guadalajara'
        | 'Guipuzcoa'
        | 'Huelva'
        | 'Huesca'
        | 'Baleares'
        | 'Jaen'
        | 'La_Coruna'
        | 'La_Rioja'
        | 'Las_Palmas'
        | 'Leon'
        | 'Lerida'
        | 'Lugo'
        | 'Madrid'
        | 'Malaga'
        | 'Murcia'
        | 'Navarra'
        | 'Orense'
        | 'Palencia'
        | 'Pontevedra'
        | 'Salamanca'
        | 'Tenerife'
        | 'Segovia'
        | 'Sevilla'
        | 'Soria'
        | 'Tarragona'
        | 'Teruel'
        | 'Toledo'
        | 'Valencia'
        | 'Valladolid'
        | 'Vizcaya'
        | 'Zamora'
        | 'Zaragoza'
      )
    | null;
  cif_dni_nie?: string | null;
  role: 'admin' | 'user' | 'pro';
  activated: boolean;
  /**
   * Marcar para enviar email de bienvenida al activar cuenta PRO
   */
  sendProEmail?: boolean | null;
  certificate?: (number | null) | Certificate;
  welcomeEmailSent?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificate".
 */
export interface Certificate {
  id: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  description?: string | null;
  image?: (number | null) | Media;
  slug?: string | null;
  slugLock?: boolean | null;
  parent?: (number | null) | Category;
  subcategories?: (number | Category)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands".
 */
export interface Brand {
  id: number;
  title: string;
  description?: string | null;
  image?: (number | null) | Media;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  title: string;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  description?: string | null;
  price: number;
  price_wholesale: number;
  stock: number;
  image?: (number | null) | Media;
  images?: ImageBlock[] | null;
  slug?: string | null;
  slugLock?: boolean | null;
  brand: number | Brand;
  tags?: (number | Tag)[] | null;
  categories: (number | Category)[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlock".
 */
export interface ImageBlock {
  img?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'image';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: number;
  product: number | Product;
  quantity: number;
  user: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  invoice_date?: string | null;
  invoice_number?: string | null;
  order_ref?: string | null;
  user_id?: string | null;
  cif_dni_nie: string;
  customer: string;
  mailing_address: string;
  mailing_city: string;
  mailing_cp: string;
  mailing_province:
    | 'Alava'
    | 'Albacete'
    | 'Alicante'
    | 'Almeria'
    | 'Asturias'
    | 'Avila'
    | 'Badajoz'
    | 'Barcelona'
    | 'Burgos'
    | 'Caceres'
    | 'Cadiz'
    | 'Cantabria'
    | 'Castellon'
    | 'Ciudad_Real'
    | 'Cordoba'
    | 'Cuenca'
    | 'Gerona'
    | 'Granada'
    | 'Guadalajara'
    | 'Guipuzcoa'
    | 'Huelva'
    | 'Huesca'
    | 'Baleares'
    | 'Jaen'
    | 'La_Coruna'
    | 'La_Rioja'
    | 'Las_Palmas'
    | 'Leon'
    | 'Lerida'
    | 'Lugo'
    | 'Madrid'
    | 'Malaga'
    | 'Murcia'
    | 'Navarra'
    | 'Orense'
    | 'Palencia'
    | 'Pontevedra'
    | 'Salamanca'
    | 'Tenerife'
    | 'Segovia'
    | 'Sevilla'
    | 'Soria'
    | 'Tarragona'
    | 'Teruel'
    | 'Toledo'
    | 'Valencia'
    | 'Valladolid'
    | 'Vizcaya'
    | 'Zamora'
    | 'Zaragoza';
  name?: string | null;
  address?: string | null;
  city?: string | null;
  cp?: string | null;
  province?:
    | (
        | 'Alava'
        | 'Albacete'
        | 'Alicante'
        | 'Almeria'
        | 'Asturias'
        | 'Avila'
        | 'Badajoz'
        | 'Barcelona'
        | 'Burgos'
        | 'Caceres'
        | 'Cadiz'
        | 'Cantabria'
        | 'Castellon'
        | 'Ciudad_Real'
        | 'Cordoba'
        | 'Cuenca'
        | 'Gerona'
        | 'Granada'
        | 'Guadalajara'
        | 'Guipuzcoa'
        | 'Huelva'
        | 'Huesca'
        | 'Baleares'
        | 'Jaen'
        | 'La_Coruna'
        | 'La_Rioja'
        | 'Las_Palmas'
        | 'Leon'
        | 'Lerida'
        | 'Lugo'
        | 'Madrid'
        | 'Malaga'
        | 'Murcia'
        | 'Navarra'
        | 'Orense'
        | 'Palencia'
        | 'Pontevedra'
        | 'Salamanca'
        | 'Tenerife'
        | 'Segovia'
        | 'Sevilla'
        | 'Soria'
        | 'Tarragona'
        | 'Teruel'
        | 'Toledo'
        | 'Valencia'
        | 'Valladolid'
        | 'Vizcaya'
        | 'Zamora'
        | 'Zaragoza'
      )
    | null;
  status?: ('R' | 'T' | 'E') | null;
  /**
   * Marcar para enviar email de actualización de estado al cliente
   */
  sendStatusEmail?: boolean | null;
  order_items: {
    product_id?: string | null;
    product_name: string;
    quantity: number;
    price: number;
    id?: string | null;
  }[];
  iva: number;
  total_iva?: number | null;
  total?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'brands';
        value: number | Brand;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'certificate';
        value: number | Certificate;
      } | null)
    | ({
        relationTo: 'carts';
        value: number | Cart;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  address?: T;
  city?: T;
  cp?: T;
  province?: T;
  mailing_name?: T;
  mailing_address?: T;
  mailing_city?: T;
  mailing_cp?: T;
  mailing_province?: T;
  cif_dni_nie?: T;
  role?: T;
  activated?: T;
  sendProEmail?: T;
  certificate?: T;
  welcomeEmailSent?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
  slug?: T;
  slugLock?: T;
  parent?: T;
  subcategories?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brands_select".
 */
export interface BrandsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  price?: T;
  price_wholesale?: T;
  stock?: T;
  image?: T;
  images?:
    | T
    | {
        image?: T | ImageBlockSelect<T>;
      };
  slug?: T;
  slugLock?: T;
  brand?: T;
  tags?: T;
  categories?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlock_select".
 */
export interface ImageBlockSelect<T extends boolean = true> {
  img?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificate_select".
 */
export interface CertificateSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  product?: T;
  quantity?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  invoice_date?: T;
  invoice_number?: T;
  order_ref?: T;
  user_id?: T;
  cif_dni_nie?: T;
  customer?: T;
  mailing_address?: T;
  mailing_city?: T;
  mailing_cp?: T;
  mailing_province?: T;
  name?: T;
  address?: T;
  city?: T;
  cp?: T;
  province?: T;
  status?: T;
  sendStatusEmail?: T;
  order_items?:
    | T
    | {
        product_id?: T;
        product_name?: T;
        quantity?: T;
        price?: T;
        id?: T;
      };
  iva?: T;
  total_iva?: T;
  total?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  slider?:
    | {
        title: string;
        subtitle?: string | null;
        image: number | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'slide';
      }[]
    | null;
  categories?: (number | Category)[] | null;
  products: {
    title: string;
    products?: (number | Product)[] | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "iva".
 */
export interface Iva {
  id: number;
  value: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-info".
 */
export interface CompanyInfo {
  id: number;
  name: string;
  address?: string | null;
  cif_dni_nie?: string | null;
  city?: string | null;
  cp?: string | null;
  province:
    | 'Alava'
    | 'Albacete'
    | 'Alicante'
    | 'Almeria'
    | 'Asturias'
    | 'Avila'
    | 'Badajoz'
    | 'Barcelona'
    | 'Burgos'
    | 'Caceres'
    | 'Cadiz'
    | 'Cantabria'
    | 'Castellon'
    | 'Ciudad_Real'
    | 'Cordoba'
    | 'Cuenca'
    | 'Gerona'
    | 'Granada'
    | 'Guadalajara'
    | 'Guipuzcoa'
    | 'Huelva'
    | 'Huesca'
    | 'Baleares'
    | 'Jaen'
    | 'La_Coruna'
    | 'La_Rioja'
    | 'Las_Palmas'
    | 'Leon'
    | 'Lerida'
    | 'Lugo'
    | 'Madrid'
    | 'Malaga'
    | 'Murcia'
    | 'Navarra'
    | 'Orense'
    | 'Palencia'
    | 'Pontevedra'
    | 'Salamanca'
    | 'Tenerife'
    | 'Segovia'
    | 'Sevilla'
    | 'Soria'
    | 'Tarragona'
    | 'Teruel'
    | 'Toledo'
    | 'Valencia'
    | 'Valladolid'
    | 'Vizcaya'
    | 'Zamora'
    | 'Zaragoza';
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  slider?:
    | T
    | {
        slide?:
          | T
          | {
              title?: T;
              subtitle?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
      };
  categories?: T;
  products?:
    | T
    | {
        title?: T;
        products?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "iva_select".
 */
export interface IvaSelect<T extends boolean = true> {
  value?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-info_select".
 */
export interface CompanyInfoSelect<T extends boolean = true> {
  name?: T;
  address?: T;
  cif_dni_nie?: T;
  city?: T;
  cp?: T;
  province?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}